// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrAMETZpjZCwOvgCp2UdCyk9GZTE0d4ZA',
    appId: '1:236253066033:web:4dba4007438aa71db43610',
    messagingSenderId: '236253066033',
    projectId: 'notes-e779e',
    authDomain: 'notes-e779e.firebaseapp.com',
    storageBucket: 'notes-e779e.firebasestorage.app',
    measurementId: 'G-WG60MDEW8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_Pm6skz_H-ucAa2RIDN639ou4eiTaBg',
    appId: '1:236253066033:android:f655505ba41c35cdb43610',
    messagingSenderId: '236253066033',
    projectId: 'notes-e779e',
    storageBucket: 'notes-e779e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhXmwyo6gi_lXc4S9AZBR8REKDpmBtH6M',
    appId: '1:236253066033:ios:6908b7d9e518c3fbb43610',
    messagingSenderId: '236253066033',
    projectId: 'notes-e779e',
    storageBucket: 'notes-e779e.firebasestorage.app',
    iosBundleId: 'com.example.vativanotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhXmwyo6gi_lXc4S9AZBR8REKDpmBtH6M',
    appId: '1:236253066033:ios:6908b7d9e518c3fbb43610',
    messagingSenderId: '236253066033',
    projectId: 'notes-e779e',
    storageBucket: 'notes-e779e.firebasestorage.app',
    iosBundleId: 'com.example.vativanotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrAMETZpjZCwOvgCp2UdCyk9GZTE0d4ZA',
    appId: '1:236253066033:web:3ece6009fe7bb6a3b43610',
    messagingSenderId: '236253066033',
    projectId: 'notes-e779e',
    authDomain: 'notes-e779e.firebaseapp.com',
    storageBucket: 'notes-e779e.firebasestorage.app',
    measurementId: 'G-NYX9MWT9SZ',
  );
}
