import "package:firebase_auth/firebase_auth.dart";
import "package:firebase_core/firebase_core.dart";
import "package:flutter/material.dart";
import "package:vativanotes/firebase_options.dart";
import "package:vativanotes/views/login_view.dart";

  // generated by flutterfire configure

void main() {
  //We do this such we dnot keep initializating firebase everytime we press a 
  // button
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MaterialApp(
    title: 'Flutter Demo',
    theme: ThemeData(
      primarySwatch: Colors.blue),
      home: const HomePage(),
    ),
  );
}

class HomePage extends StatelessWidget {
  const new({super.key});

  @override
  Widget build(BuildContext context) {
    // #the Scaffold is the owner of the white content here
    return Scaffold(
      // AppBar is the heading
      appBar: AppBar(
        title: const Text('HomePage'),
      ),
      // We Wrap our Body in the center
      //  We Use Flutter Builder to do a future before
      // So before we build a column , we are going to build a firebase initialization
      // because we dnot want to keep on initalizing a firbase
      body: FutureBuilder(
        future: Firebase.initializeApp(
                options: DefaultFirebaseOptions.currentPlatform,
                ),
        builder: (context, asyncSnapshot) {
          // So Connection State tells us what is the state of our Future 
          switch (asyncSnapshot.connectionState){
            case ConnectionState.done:
                  final user = FirebaseAuth.instance.currentUser;
                  
                  if (user?.emailVerified ?? false){
                    print("You are a verified user");
                  }
                  else{
                    print("You are not verified");
                  }
                return const Text("Done");
              default:
              return const Text('Loading');
          }
          
        }
      ),
    );
  }
}
